trigger:
- main
- develop
- feature/*

pool:
  vmImage: macos-latest

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  inputs:
    target: 'apk'
    projectDirectory: '.'
    buildNumber: '$(Build.BuildId)'
- task: FlutterCommand@0
  inputs:
    arguments: 'analyze'
    projectDirectory: '.'
- task: FlutterTest@0
  inputs:
    projectDirectory: '.'
