name: tatetsu
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^0.1.3
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  test:

flutter:
  uses-material-design: true
