name: tatetsu
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  english_words: ^4.0.0
  firebase_analytics: ^10.1.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.10
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.1
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.1
  google_mobile_ads: ^2.3.0
  intl: ^0.17.0
  japanese_family_name_generator: ^0.0.1
  json_annotation: ^4.7.0
  share_plus: ^6.3.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  lint:
  test:

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
