name: tatetsu
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^0.1.3
  english_words: ^4.0.0
  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.1
  flutter:
    sdk: flutter
  flutter_flavor: ^3.0.3
  flutter_localizations:
    sdk: flutter
  google_mobile_ads: ^1.1.0
  intl: ^0.17.0
  japanese_family_name_generator: ^0.0.1
  json_annotation: ^4.7.0
  share_plus: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  lint:
  test:

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
