# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

api_key_path("appstore_api_key.json")
force(true)
price_tier(0)
ipa("build/ios/ipa/tatetsu.ipa")
app_rating_config_path("fastlane/metadata/app_rating_config.json")
precheck_include_in_app_purchases(false)
